/* */

export const authActionTypes = {
  /* */

  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

  ALL_USERS_REQUEST: "ALL_USERS_REQUEST",
  ALL_USERS_SUCCESS: "ALL_USERS_SUCCESS",
  ALL_USERS_FAIL: "ALL_USERS_FAIL",

  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  DELETE_ACCESS_TOKEN: "DELETE_ACCESS_TOKEN",

  /* */
};

export const ticketActionTypes = {
  /* */

  TICKET_SEND_START: "TICKET_SEND_START",
  TICKET_SEND_SUCCESS: "TICKET_SEND_SUCCESS",
  TICKET_SEND_FAILURE: "TICKET_SEND_FAILURE",

  SET_ALL_TICKETS: "SET_ALL_TICKETS",

  /* */
};

export const bookActionTypes = {
  /* */

  BOOK_SEND_START: "BOOK_SEND_START",
  BOOK_SEND_SUCCESS: "BOOK_SEND_SUCCESS",
  BOOK_SEND_FAILURE: "BOOK_SEND_FAILURE",

  SET_ALL_BOOKS: "SET_ALL_BOOKS",

  /* */
};

export const photoActionTypes = {
  /* */

  ALL_PHOTO_REQUEST: "ALL_PHOTO_REQUEST",

  ALL_PHOTO_SUCCESS: "ALL_PHOTO_SUCCESS",

  ALL_PHOTO_FAIL: "ALL_PHOTO_FAIL",

  /* */
};

export const serviceActionTypes = {
  /* */

  ALL_SERVICES_REQUEST: "ALL_SERVICES_REQUEST",
  ALL_SERVICES_SUCCESS: "ALL_SERVICES_SUCCESS",
  ALL_SERVICES_FAIL: "ALL_SERVICES_FAIL",

  /* */
};

export const billingActionTypes = {
  /* */

  CREATE_BILLING_START: "CREATE_BILLING_START",
  CREATE_BILLING_SUCCESS: "CREATE_BILLING_SUCCESS",
  CREATE_BILLING_FAILURE: "CREATE_BILLING_FAILURE",

  SET_BILLING_DETAILS: " SET_BILLING_DETAILS",

  /* */
};

export const verificationActionTypes = {
  /* */

  DOING_VERIFICATION_START: "DOING_VERIFICATION_START",

  /* */
};
