/* */

export const photos = [
  /* */

  /* ******************************* */
  /* Flood */
  /* ******************************* */

  "help/flood1.jfif",
  "help/flood2.jfif",
  "help/flood3.jfif",
  "help/flood4.jfif",
  "help/flood6.jfif",
  "help/flood7.jfif",
  "help/flood8.jfif",
  "help/flood9.jfif",
  "help/flood10.jfif",
  "help/flood11.jfif",
  "help/flood12.jfif",
  "help/flood13.jfif",
  "help/flood14.jfif",
  "help/flood15.jfif",
  "help/flood16.jfif",
  "help/flood17.jfif",
  "help/flood18.jfif",
  "help/flood19.jfif",
  "help/flood20.jfif",
  "help/flood21.jfif",
  "help/flood22.jfif",
  "help/flood23.jpg",

  "newImages/inaugaration4.jpg",
  "newImages/inaugaration1.jfif",
  "newImages/inaugaration2.jfif",

  // "mainImages/kamalaStatue.jpg",
  "mainImages/pronob5.jpg",
  "mainImages/pronob4.jpg",
  "mainImages/pronob1.jpg",
  "mainImages/pronob2.jpg",

  "mainImages/falicitation1.jfif",
  "mainImages/falicitation2.jfif",
  "mainImages/falicitation3.jfif",
  "mainImages/falicitation4.jfif",
  "mainImages/falicitation5.jfif",
  "mainImages/falicitation6.jfif",

  "mainImages/matric1.jpeg",
  "mainImages/certificate23.jpg",
  "mainImages/hemanta.jpg",

  "mainImages/pronob6.jfif",

  "mainImages/kamala1.jfif",
  "mainImages/kamalaMiri2.jpg",

  "certificates/certificate0.jfif",

  /* *************************************** */

  "certificates/newCertificate1.jfif",
  "certificates/newCertificate2.jfif",
  "certificates/newCertificate3.jfif",
  "certificates/newCertificate4.jfif",
  "certificates/newCertificate5.jfif",
  "certificates/newCertificate6.jfif",
  "certificates/newCertificate7.jfif",
  "certificates/newCertificate8.jfif",
  "certificates/newCertificate9.jfif",
  "certificates/newCertificate10.jfif",
  "certificates/newCertificate11.jfif",
  "certificates/newCertificate12.jfif",
  "certificates/newCertificate13.jfif",
  "certificates/newCertificate14.jfif",

  /* *************************************** */

  "mainImages/certificate0.jpg",
  "mainImages/certificate22.jpg",
  "mainImages/certificate1.jpg",
  "mainImages/certificate2.jpg",
  "mainImages/certificate3.jpg",
  "mainImages/certificate4.jpg",
  "mainImages/certificate5.jpg",
  "mainImages/certificate6.jpg",
  "mainImages/certificate7.jpg",
  "mainImages/certificate9.jpg",
  "mainImages/certificate10.jpg",
  "mainImages/certificate11.jpg",
  "mainImages/certificate12.jpg",
  "mainImages/certificate14.jpg",
  "mainImages/certificate15.jpg",
  "mainImages/certificate16.jpg",
  "mainImages/certificate17.jpg",
  "mainImages/certificate18.jpg",
  "mainImages/certificate19.jpg",
  "mainImages/certificate20.jpg",
  "mainImages/certificate21.jpg",
  "mainImages/certificate24.jpg",
  "mainImages/certificate25.jpg",
  "mainImages/certificate26.jfif",
  "mainImages/certificate27.jfif",
  "mainImages/certificate28.jfif",
  "mainImages/certificate29.jfif",
  "mainImages/certificate30.jfif",
  "mainImages/certificate31.jpg",
  "mainImages/certificate32.jfif",
  "mainImages/certificate33.jpg",
  "mainImages/certificate35.jfif",
  "mainImages/certificate36.jfif",
  "mainImages/certificate37.jfif",
  "mainImages/certificate38.jpg",
  "mainImages/certificate39.jpg",
  "mainImages/certificate40.jfif",
  "mainImages/certificate41.jpg",
  "mainImages/certificate42.jfif",
  "mainImages/certificate43.jfif",
  "mainImages/certificate44.jfif",
  "mainImages/certificate45.jfif",
  "mainImages/certificate46.jfif",
  "mainImages/certificate47.jfif",
  "mainImages/certificate48.jfif",
  "mainImages/certificate49.jfif",
  "mainImages/certificate50.jfif",
  "mainImages/certificate51.jfif",

  /* ******************************************************* */
  /* CERTIFICATES : */
  /* ******************************************************* */

  "certificates/certificate1.jpg",
  "certificates/certificate2.jfif",
  "certificates/certificate3.jfif",
  "certificates/certificate4.jfif",
  "certificates/certificate5.jfif",
  "certificates/certificate6.jpg",
  "certificates/certificate7.jpg",
  "certificates/certificate8.jpg",
  "certificates/certificate9.jpg",
  "certificates/certificate10.jfif",
  "certificates/certificate11.jfif",
  "certificates/certificate12.jfif",
  "certificates/certificate13.jpg",
  "certificates/certificate14.jfif",
  "certificates/certificate15.jfif",
  "certificates/certificate16.jfif",
  "certificates/certificate17.jfif",
  "certificates/certificate18.jpg",
  "certificates/certificate19.jfif",
  "certificates/certificate20.jfif",
  "certificates/certificate21.jfif",
  "certificates/certificate22.jfif",
  "certificates/certificate23.jfif",
  "certificates/certificate24.jfif",
  "certificates/certificate25.jfif",
  "certificates/certificate26.jfif",
  "certificates/certificate27.jfif",
  "certificates/certificate28.jfif",
  "certificates/certificate29.jfif",
  "certificates/certificate30.jfif",
  "certificates/certificate31.jfif",
  "certificates/certificate32.jfif",
  "certificates/certificate33.jfif",
  "certificates/certificate34.jpg",
  "certificates/certificate35.jfif",
  "certificates/certificate36.jfif",
  "certificates/certificate37.jfif",
  "certificates/certificate38.jfif",
  "certificates/certificate39.jfif",
  "certificates/certificate40.jpg",
  "certificates/certificate41.jfif",
  "certificates/certificate42.jfif",
  "certificates/certificate43.jfif",
  "certificates/certificate44.jfif",
  "certificates/certificate45.jfif",
  "certificates/certificate46.jfif",
  "certificates/certificate47.jfif",
  "certificates/certificate48.jfif",
  "certificates/certificate49.jfif",
  "certificates/certificate50.jfif",
  "certificates/certificate51.jfif",
  "certificates/certificate52.jfif",
  "certificates/certificate53.jpg",
  "certificates/certificate54.jfif",
  "certificates/certificate55.jfif",
  "certificates/certificate56.jfif",
  "certificates/certificate57.jpg",
  "certificates/certificate58.jfif",
  "certificates/certificate59.jfif",
  "certificates/certificate60.jfif",
  "certificates/certificate61.jpg",
  "certificates/certificate62.jpg",
  "certificates/certificate63.jpg",
  "certificates/certificate64.jfif",
  "certificates/certificate65.jfif",
  "certificates/certificate66.jpg",
  "certificates/certificate67.jfif",
  "certificates/certificate68.jfif",
  "certificates/certificate69.jfif",
  "certificates/certificate70.jfif",
  "certificates/certificate71.jfif",
  "certificates/certificate72.jfif",
  "certificates/certificate73.jfif",
  "certificates/certificate74.jfif",
  "certificates/certificate75.jpg",
  "certificates/certificate76.jfif",
  "certificates/certificate77.jpg",
  "certificates/certificate78.jfif",
  "certificates/certificate79.jfif",
  "certificates/certificate80.jfif",
  "certificates/certificate81.jfif",
  "certificates/certificate82.jfif",
  "certificates/certificate83.jfif",
  "certificates/certificate84.jfif",
  "certificates/certificate85.jfif",
  "certificates/certificate86.jfif",
  "certificates/certificate87.jfif",
  "certificates/certificate88.jfif",
  "certificates/certificate89.jfif",
  "certificates/certificate90.jfif",
  "certificates/certificate91.jfif",
  "certificates/certificate92.jfif",
  "certificates/certificate93.jfif",
  "certificates/certificate94.jfif",
  "certificates/certificate95.jfif",
  "certificates/certificate96.jfif",
  "certificates/certificate97.jfif",
  "certificates/certificate98.jfif",
  "certificates/certificate99.jfif",
  "certificates/certificate100.jfif",
  "certificates/certificate101.jfif",
  "certificates/certificate102.jfif",
  "certificates/certificate103.jpg",
  "certificates/certificate104.jfif",
  "certificates/certificate105.jfif",
  "certificates/certificate106.jfif",
  "certificates/certificate107.jfif",
  "certificates/certificate108.jfif",
  "certificates/certificate109.jfif",
  "certificates/certificate110.jfif",
  "certificates/certificate111.jfif",
  "certificates/certificate112.jfif",
  "certificates/certificate113.jfif",
  "certificates/certificate114.jpg",

  /* ******************************************************* */
  /* OTHERS IMAGES : */
  /* ******************************************************* */

  "others/nature2.jpg",
  "others/gaon10.jpeg",
  "others/gaon15.jpeg",
  "others/missingTribe.webp",
  "others/missingTribe2.jpg",
  "others/mishingfood2.JPG",
  "others/MISHINGdress.jpg",
  "others/pork.jpeg",
  "others/fishingNew2.png",
  "others/TeaGarden.webp",
  "others/missingTribe1.webp",

  /* */
];
